shellEmulator: true
trustPolicy: no-downgrade
packages:
  - playground
  - client
  - docs
overrides:
  sharp: 0.33.5
  typescript: 5.6.3
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - keytar
  - sharp
  - unrs-resolver
  - vue-demi
