shellEmulator: true
trustPolicy: no-downgrade
packages:
  - playground
  - client
  - docs
overrides:
  '@nuxt/devtools': 3.3.1
  '@nuxt/devtools-kit': 3.2.4
  '@nuxt/devtools-ui-kit': 3.2.4
  '@nuxt/kit': 4.4.2
  '@nuxt/schema': 4.4.2
  '@vue/compiler-core': 3.5.32
  '@vue/compiler-dom': 3.5.32
  '@vue/compiler-sfc': 3.5.32
  '@vitejs/plugin-vue': 6.0.5
  chokidar: ^5.0.0
  fast-uri: ^3.1.5
  form-data: ^4.0.6
  nanoid: ^3.3.18
  nuxt: 4.4.2
  'picomatch@<2.3.2': ^2.3.2
  'picomatch@>=4.0.0 <4.0.4': ^4.0.4
  postcss: ^8.5.23
  rollup: 4.59.0
  semver: ^7.7.4
  sharp: 0.33.5
  shell-quote: ^1.10.0
  tar: ^7.5.22
  typescript: 5.6.3
  vite: ^7.3.5
  vue: 3.5.32
onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - keytar
  - sharp
  - unrs-resolver
  - vue-demi
