shellEmulator: true
shamefullyHoist: true
trustPolicy: no-downgrade
packages:
  - playground
  - client
  - docs
overrides:
  '@nuxt/devtools': 3.4.0
  '@nuxt/devtools-kit': 3.4.0
  '@nuxt/devtools-ui-kit': 3.4.0
  '@nuxt/kit': 4.5.2
  '@nuxt/schema': 4.5.2
  '@vue/compiler-core': 3.5.41
  '@vue/compiler-dom': 3.5.41
  '@vue/compiler-sfc': 3.5.41
  '@vitejs/plugin-vue': 6.0.8
  chokidar: ^5.0.0
  fast-uri: ^4.1.2
  form-data: ^4.0.6
  nanoid: ^6.0.1
  nuxt: 4.5.2
  'picomatch@<2.3.2': ^2.3.2
  'picomatch@>=4.0.0 <4.0.4': ^4.0.5
  postcss: ^8.5.26
  rollup: 4.62.4
  semver: ^7.8.5
  sharp: 0.35.3
  shell-quote: ^1.10.0
  tar: ^7.5.22
  typescript: 6.0.3
  vite: ^8.2.1
  vue: 3.5.41
minimumReleaseAgeExclude:
  - concurrently@10.0.5
  - jose@6.2.9
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  keytar: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
