[project]
name = "nuxt-oidc-auth"
revision = "1.0"
require_reason = false

[providers]
e2e = "onepassword://nuxt-oidc-auth"

[profiles.default]
NUXT_OIDC_AUTH_SESSION_SECRET = { description = "OIDC authorization session encryption secret", required = true }
NUXT_OIDC_SESSION_SECRET = { description = "OIDC user session encryption secret", required = true }
NUXT_OIDC_TOKEN_KEY = { description = "OIDC token encryption key", required = true }
NUXT_OIDC_PROVIDERS_AUTH0_CLIENT_ID = { description = "Auth0 client ID", required = false }
NUXT_OIDC_PROVIDERS_AUTH0_CLIENT_SECRET = { description = "Auth0 client secret", required = false }
NUXT_OIDC_PROVIDERS_AUTH0_BASE_URL = { description = "Auth0 tenant base URL", required = false }
NUXT_OIDC_PROVIDERS_COGNITO_CLIENT_ID = { description = "AWS Cognito client ID", required = false }
NUXT_OIDC_PROVIDERS_COGNITO_CLIENT_SECRET = { description = "AWS Cognito client secret", required = false }
NUXT_OIDC_PROVIDERS_COGNITO_BASE_URL = { description = "AWS Cognito user-pool base URL", required = false }
NUXT_OIDC_PROVIDERS_ENTRA_CLIENT_ID = { description = "Microsoft Entra client ID", required = false }
NUXT_OIDC_PROVIDERS_ENTRA_CLIENT_SECRET = { description = "Microsoft Entra client secret", required = false }
NUXT_OIDC_PROVIDERS_ENTRA_TENANT_ID = { description = "Microsoft Entra tenant ID", required = false }
NUXT_OIDC_PROVIDERS_GITHUB_CLIENT_ID = { description = "GitHub OAuth client ID", required = false }
NUXT_OIDC_PROVIDERS_GITHUB_CLIENT_SECRET = { description = "GitHub OAuth client secret", required = false }
NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID = { description = "Keycloak client ID", required = false, default = "nuxt-oidc-test" }
NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_SECRET = { description = "Keycloak client secret", required = false, default = "nuxt-oidc-test-secret" }
NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL = { description = "Keycloak realm base URL", required = false, default = "http://localhost:8080/realms/nuxt-oidc-test" }
NUXT_OIDC_PROVIDERS_LOGTO_CLIENT_ID = { description = "Logto client ID", required = false }
NUXT_OIDC_PROVIDERS_LOGTO_CLIENT_SECRET = { description = "Logto client secret", required = false }
NUXT_OIDC_PROVIDERS_LOGTO_BASE_URL = { description = "Logto tenant base URL", required = false }
NUXT_OIDC_PROVIDERS_MICROSOFT_CLIENT_ID = { description = "Microsoft client ID", required = false }
NUXT_OIDC_PROVIDERS_MICROSOFT_CLIENT_SECRET = { description = "Microsoft client secret", required = false }
NUXT_OIDC_PROVIDERS_PAYPAL_CLIENT_ID = { description = "PayPal client ID", required = false }
NUXT_OIDC_PROVIDERS_PAYPAL_CLIENT_SECRET = { description = "PayPal client secret", required = false }
NUXT_OIDC_PROVIDERS_ZITADEL_CLIENT_ID = { description = "Zitadel client ID", required = false }
NUXT_OIDC_PROVIDERS_ZITADEL_CLIENT_SECRET = { description = "Zitadel client secret", required = false }
NUXT_OIDC_PROVIDERS_ZITADEL_BASE_URL = { description = "Zitadel tenant base URL", required = false }
