#!/usr/bin/env sh
set -eu

export NUXT_OIDC_AUTH_SESSION_SECRET=test-auth-session-secret-at-least-48-characters-long
export NUXT_OIDC_DEFAULT_PROVIDER=oidc
export NUXT_OIDC_PROVIDERS_OIDC_AUDIENCE=nuxt-oidc-test
export NUXT_OIDC_PROVIDERS_OIDC_AUTHORIZATION_URL=http://127.0.0.1:5556/dex/auth/mock
export NUXT_OIDC_PROVIDERS_OIDC_CLIENT_ID=nuxt-oidc-test
export NUXT_OIDC_PROVIDERS_OIDC_CLIENT_SECRET=nuxt-oidc-test-secret
export NUXT_OIDC_PROVIDERS_OIDC_REDIRECT_URI=http://localhost:31840/auth/oidc/callback
export NUXT_OIDC_PROVIDERS_OIDC_TOKEN_URL=http://127.0.0.1:5556/dex/token
export NUXT_OIDC_PROVIDERS_OIDC_USER_INFO_URL=http://127.0.0.1:5556/dex/userinfo
export NUXT_OIDC_PROVIDERS_KEYCLOAK_AUTHORIZATION_URL=http://127.0.0.1:5557/authorize
export NUXT_OIDC_PROVIDERS_KEYCLOAK_BASE_URL=http://127.0.0.1:5557
export NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_ID=browser-client
export NUXT_OIDC_PROVIDERS_KEYCLOAK_CLIENT_SECRET=browser-secret
export NUXT_OIDC_PROVIDERS_KEYCLOAK_LOGOUT_URL=http://127.0.0.1:5557/logout
export NUXT_OIDC_PROVIDERS_KEYCLOAK_NONCE=false
export NUXT_OIDC_PROVIDERS_KEYCLOAK_PKCE=false
export NUXT_OIDC_PROVIDERS_KEYCLOAK_STATE=true
export NUXT_OIDC_PROVIDERS_KEYCLOAK_VALIDATE_ACCESS_TOKEN=false
export NUXT_OIDC_PROVIDERS_KEYCLOAK_VALIDATE_ID_TOKEN=false
export NUXT_OIDC_PROVIDERS_KEYCLOAK_SINGLE_SIGN_OUT=false
export NUXT_OIDC_PROVIDERS_KEYCLOAK_EXPIRATION_CHECK=false
export NUXT_OIDC_PROVIDERS_KEYCLOAK_TOKEN_URL=http://127.0.0.1:5557/token
export NUXT_OIDC_PROVIDERS_KEYCLOAK_USER_INFO_URL=http://127.0.0.1:5557/userinfo
export NUXT_OIDC_SESSION_SECRET=test-user-session-secret-at-least-48-characters-long
export NUXT_OIDC_TOKEN_KEY=MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWY=
export PORT=31840

echo OFFLINE_NUXT_PRODUCTION_BUILD=1 >&2
pnpm exec nuxt build test/fixtures/oidcApp
exec node test/fixtures/oidcApp/.output/server/index.mjs
